services:
  postgres:
    image: postgres:latest
    container_name: gw-postgres
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: somew0rds
      POSTGRES_DB: GamersWorldDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data
    networks:
      - gw-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: gw-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: scoth@tiger.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - gw-network

volumes:
  postgres_data:

networks:
  gw-network:
    driver: bridge